version: "3"
services:
  storage:
    image: nginx:1.14-alpine
    ports:
      - 3000:80
    volumes:
      - "./workspaces/storage-mock/public:/var/www/html"
      - "./workspaces/storage-mock/default.conf:/etc/nginx/conf.d/default.conf"
